# Generated by Django 4.1 on 2022-09-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_kb_data_lease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='price',
            new_name='Date_of_deliver',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='category',
            new_name='EIA',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='description',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='name',
            new_name='Nationality',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='date_created',
        ),
        migrations.AddField(
            model_name='lease',
            name='Phone_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='Plan_agreement_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='Site_plan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='Starting_of_Building',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='Title_deeded_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='finishing_of_building',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='permission_of_building_date',
            field=models.DateTimeField(null=True),
        ),
    ]
