# Generated by Django 4.1 on 2022-09-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_price_lease_date_of_deliver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='Date_of_deliver',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='EIA',
            field=models.CharField(choices=[('HAVE', 'HAVE'), ('HAVE NO', 'HAVE NO')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='Plan_agreement_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='Site_plan',
            field=models.CharField(choices=[('HAVE', 'HAVE'), ('HAVE NO', 'HAVE NO')], max_length=200, null=True),
        ),
    ]
