# Generated by Django 4.1 on 2022-09-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_lease_date_of_deliver_alter_lease_eia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projects')),
            ],
        ),
        migrations.DeleteModel(
            name='KB_data',
        ),
    ]
