# Generated by Django 4.1 on 2022-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
