# Generated by Django 4.1 on 2022-09-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_projects_user_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
