# Generated by Django 4.1 on 2022-09-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
