# Generated by Django 4.1 on 2022-09-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_owner_owner_projects_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project',
            new_name='owner',
        ),
    ]
