# Generated by Django 4.1 on 2022-09-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projects_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
