# Generated by Django 4.1 on 2022-09-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_lease_documents_alter_owner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='Documents',
            new_name='Lease_agreement_and_other_documents',
        ),
    ]
