# Generated by Django 4.1 on 2022-09-13 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0017_rename_documents_lease_lease_agreement_and_other_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lease',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
