# Generated by Django 4.1 on 2022-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_request_capital_request_file_request_jobcreation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
