# Generated by Django 4.1 on 2022-10-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=200, null=True),
        ),
    ]
