# Generated by Django 4.1 on 2022-10-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='projectcluster',
            field=models.CharField(choices=[('agro-processing', 'agro-processing'), ('wood and metals', 'wood and metals'), ('pharmaciotical', 'pharmaciotical'), ('plastic and chemical', 'plastic and chemical'), ('textile and leather-products', 'textile and leather-products')], max_length=200, null=True),
        ),
    ]
